### ISSUE TITLE
About your Closest-Pair-Problem-CUDA repository

### ISSUE THREAD

**Issue by medina325** [GeorgePapageorgakis/Closest-Pair-Problem-CUDA#1]
Hello! I want to use your work to compare it's results / performance with mine.

Since there are no instructions on how to run your solution, do you mind telling me how can I run it?

Hope hearing from you soon. Thank you!

**Comment by GeorgePapageorgakis** [comment]
Hello medina.
Ofcourse you can try it but the code has a bug and i have never uploaded the corrected version.
The bug is in sorting and searching.  I mean i resort the initial array everytime i move on a step in the closest pair algorithm while the correct approach is to keep the sorted batches, perform the closest pair each time after merge sort is called, and repeat until you have one batch in the end. The versions here are really slow, like x20 only speed due to sorting.

To run the code just include all files in a new project in VS with cuda api 5+.

**Comment by medina325** [comment]
Hello George.

I actually found your paper "Development of the Closest Pair algorithm with CUDA API". But since the paper is in Greek, can you please tell me if the brute force CUDA solution works correctly?

I've been running it and it seems right, but I must be sure so I can use as reference in my paper.

Thank you,
Gabriel
________________________________

**Comment by GeorgePapageorgakis** [comment]
Hello and sorry for the delayed answer. Yes the brute force works great.
CUDA code also works but I havent uploaded the correct version. There was a bug when sorting each batch over from the start making the algorithm extremely slow.
By doing the steps:

sort baches only one step->merge->find potential closest pairs -> repeat 

is way faster than doing:

resort the whole initial array up to the batches needed->merge->find potential closest pairs -> repeat

you can gain up to x500 speedup.

Cheers
